export {default as Home} from './Home'
export {default as Blogs} from './Blogs'
export {default as Product} from './Product'
export {default as Blog} from './Blog'
export {default as UserPreferences} from './UserPreferences'
export {default as EditBlog} from './EditBlog'
